name: Renovate

on:
  schedule:
    - cron: '0 9 * * *'  # 3am CT (UTC-6)
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        run: renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_PLATFORM: gitea
          RENOVATE_ENDPOINT: https://git.planetixian.com/api/v1
          RENOVATE_CONFIG_FILE: default.json
          LOG_LEVEL: debug
